#!/usr/bin/env node

const createReporter = require('ohcrash');
const reporter = createReporter('test', {
  uncaughtExceptions: false,
  exit: false,
  unhandledRejections: false,
  windowOnError: false,
  endpoint: `http://localhost:${process.argv[2]}/api/v1`
});

reporter.report(new Error('fake'));
